### ISSUE TITLE
Multiple imports in one single line

### ISSUE THREAD

**Issue by phdoerfler** [liancheng/scalafix-organize-imports#155]
Imports such as this:

```scala
import io.circe._, io.circe.generic.auto._, io.circe.generic.semiauto._, io.circe.parser._, io.circe.generic.extras._, io.circe.syntax._
```

are not unheard of and I would appreciate if I could configure scalafix so that it would not tear them apart into this:

```scala
import io.circe._
import io.circe.generic.auto._
import io.circe.generic.extras._
import io.circe.generic.semiauto._
import io.circe.parser._
import io.circe.syntax._
```

but leave them together in their single line. It could (and I suppose it _should_) still treat them like other imports in other regards such as sorting. Just don't break them up.

Thanks for your thoughts on this!

**Comment by liancheng** [comment]
Hi @phdoerfler, thanks for the feedback! In which case(s) would you like to have multiple imports kept on a single line? Is it for dealing with legacy codebases where you want to minimize changes introduced by source formatting tools?

It is doable to add a new option, say `multiImportExpressions`, to specify how to deal with import statements with multiple import expressions. It can have three possible values:

- `Explode`: The current semantics, i.e., move each import expression into a separate import statement.
- `Sort`: Still keep it on a single line, but sort all the import expressions by the order specified by the `importOrder` option (`Ascii` or `SymbolsFirst`).
- `Keep`: Leave it as is.

I personally don't anything other than `Explode` because:

1. It's lengthy and can easily pass the line margin.
1. Having multiple import expressions on a single line is not version control friendly. Any changes made to multiple import expressions on that line only result in a single line of change in the diff, which makes it hard to review and revert.

For similar reasons, the [`groupedImports` option][1] also defaults to [`Explode`][2].

[1]: https://github.com/liancheng/scalafix-organize-imports/tree/v0.5.0#groupedImports
[2]: https://github.com/liancheng/scalafix-organize-imports/tree/v0.5.0#262-default-value
