### ISSUE TITLE
Support Symbol first for sorting imports (not grouped imports)

### ISSUE THREAD

**Issue by slandelle** [liancheng/scalafix-organize-imports#20]
Similar to https://github.com/NeQuissimus/sort-imports/issues/47 that we recently implemented.

Different from `importSelectorsOrder` that sorts grouped imports.

Currently, scalafix-organize-imports only supports ASCII sort order, which is taken from Google's Java style guide.
However, this rule defeats the original purpose which is to have wildcard imports first and then sub-packages. ASCII sort order works fine in Java as the wildcard is `*` that comes before alphanum chars in the ASCII table.
But sadly the Scala wildcard `_` and the `{` for grouped imports come after.

What we currently have:

```scala
import foo.bar.baz
import foo.bar.{ Foo, Bar }
import foo._
```

What we want:

```scala
import foo._
import foo.bar.{ Foo, Bar }
import foo.bar.baz
```

**Comment by liancheng** [comment]
Hey @slandelle, thanks for the feedback!

I think it's good to have this sorting convention since it's the default way the IntelliJ IDEA Scala plugin sorts import. I believe there are lots of existing codebases that are already using this convention and don't want to introduce a big diff when adopting `OrganizeImports`.

However, I personally still prefer the ASCII sort order. It's easy to sort imports by ASCII code using almost any non-trivial text editor without any using any 3rd party tools/plugins. We can have a `importsOrder` configuration, with `Ascii`, `SymbolsFirst`, and `Keep` options, and defaults to `Ascii`.

**Comment by slandelle** [comment]
> We can have a importsOrder configuration, with Ascii, SymbolsFirst, and Keep options, and defaults to Ascii.

That's exactly what I'm asking for: not changing the default behavior but introducing a new dedicated option. Thanks for considering.

**Comment by liancheng** [comment]
@slandelle, PR #23 implements this, PTAL.
